// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHtw3y1UO3uIjT5ABvVXRGLssFMF9VPOk',
    appId: '1:347459708654:web:8d650fa7b8f19de50d75ff',
    messagingSenderId: '347459708654',
    projectId: 'fruit-hub-b706a',
    authDomain: 'fruit-hub-b706a.firebaseapp.com',
    storageBucket: 'fruit-hub-b706a.firebasestorage.app',
    measurementId: 'G-MH4QLXRREW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq_ckSeX6_bxnqdtDUJajEsZ1PlKOtIZM',
    appId: '1:347459708654:android:14452e1bdcc1365b0d75ff',
    messagingSenderId: '347459708654',
    projectId: 'fruit-hub-b706a',
    storageBucket: 'fruit-hub-b706a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO6MmiHvMv4_xJ5ajx5W5oR4gitl1Qm-I',
    appId: '1:347459708654:ios:360f7dc09ca96f5d0d75ff',
    messagingSenderId: '347459708654',
    projectId: 'fruit-hub-b706a',
    storageBucket: 'fruit-hub-b706a.firebasestorage.app',
    androidClientId: '347459708654-nufef4bld3cstb88cqoavglujpnj1u8b.apps.googleusercontent.com',
    iosClientId: '347459708654-h36moehgmpu5apo8kvj1h27o6rf1pokd.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitHubDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO6MmiHvMv4_xJ5ajx5W5oR4gitl1Qm-I',
    appId: '1:347459708654:ios:360f7dc09ca96f5d0d75ff',
    messagingSenderId: '347459708654',
    projectId: 'fruit-hub-b706a',
    storageBucket: 'fruit-hub-b706a.firebasestorage.app',
    androidClientId: '347459708654-nufef4bld3cstb88cqoavglujpnj1u8b.apps.googleusercontent.com',
    iosClientId: '347459708654-h36moehgmpu5apo8kvj1h27o6rf1pokd.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitHubDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHtw3y1UO3uIjT5ABvVXRGLssFMF9VPOk',
    appId: '1:347459708654:web:d5440d303b00b8920d75ff',
    messagingSenderId: '347459708654',
    projectId: 'fruit-hub-b706a',
    authDomain: 'fruit-hub-b706a.firebaseapp.com',
    storageBucket: 'fruit-hub-b706a.firebasestorage.app',
    measurementId: 'G-G6H475BZ7X',
  );
}
